### ISSUE TITLE
Populate SD card sees 8 slots on R3

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-fdisk#20]
R3 boards only have 4, not 8 flash slots, but fdisk sees them twice for the SD-Card pre-population (please see screenshot)

![Snapshot_20230202_135717](https://user-images.githubusercontent.com/3924427/216332232-844aebaf-42a2-47e1-9eb6-c5fb0715f0e2.jpg)

**Comment by lydon42** [comment]
The only way this  could be changed is by letting MEGAFLASH write some info about the QSPI in some upper memory area, so fdisk (and/or other tools) can look it up there.
QSPI access is limited to HYPPO and DIP #3 special bootup, so by default there is no way for the program to determine where the flash ends.

Different solution: just suppress slots that read exactly the same as the slots already in the list.
