### ISSUE TITLE
ASCII font lacks Unicode Latin1 symbols

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-fdisk#3]
MEGA65 ASCII keyboard input hardware accelerator now supports a variety of Latin1 code page symbols from Unicode via the ALT key. For example, ALT + [ should yield Ö and ALT + ; should yield ö.

Table of symbols to add from this wikipedia page:

https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)

Symbols 0x80 - 0x9F can be left blank, as they are control code.
Almost all the rest can be typed using the ALT key, however.

The file ascii00-7f.png needs to be made 256x8 pixels tall, and the missing glyphs added. It should then be renamed to ascii00-ff.png, and the build infrastructure updated to reflect it.

Once done, the updated font should then also be copied into the other repositories where it is used, such as mega65-core in the assets directory.

**Comment by lydon42** [comment]
Was added in ec9ae78ad7cab3ea3a600457286d44ba4734bb96
