### ISSUE TITLE
Formatter defaults to internal SD card while an external Micro SD is inserted

### ISSUE THREAD

**Issue by RalphEgas** [MEGA65/mega65-fdisk#4]
The external Micro SD port supposedly takes over from the internal SD port when a Micro SD is inserted. The system will try to boot from the external SD as such.

However, in order to create a compatible structure, one has to use the FDISK formatter utility. Running this utility seems to only consider the internal SD card and as such will overwrite that one instead of the external one that should in fact override the internal one.

**Comment by RalphEgas** [comment]
OK, just removed the internal one to check whether the utility is addressing the external one or not and now it wants to format the external one. Well, at least it doesn't complain about a 'missing card'. It looks exactly like what happened before. The card doesn't get properly recognised as it turns out. I'm using a 32GB Micro SD that is identified as having only 57 MiB. I guess it's not the right kind (can't tell, the writing is blurred on the card). Now, this means, that if an external card is not the right one, it will end up formatting the internal one but won't let the user know this. At least that could be what's happening. Just saying that it may not just default to the internal card in all cases.

**Comment by gardners** [comment]
Fixed, and will be pulled in as part of issue 215 of mega65-core
