### ISSUE TITLE
FDISK confuses internal and external slot

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-fdisk#7]
MEGA FDISK+FORMAT V00.08 confuses internal and external SD card.
An internal card is dectected as external SD 0, an external card is detected as internal SD 1.
I've tested this with only one card inserted at a time.

**Comment by gardners** [comment]
As far as I can see, it displays the incorrect bus number, but correct internal/external indication.

**Comment by Edilbert** [comment]
![P1050345](https://user-images.githubusercontent.com/6380947/87760889-ce09c480-c810-11ea-9f02-91df81f8cdb0.JPG)
This is the FDISK screen, if only the internal SD card is mounted. The external slot is empty.

**Comment by gardners** [comment]
Ah, gotcha.  Let me have another poke at it.

**Comment by gardners** [comment]
Ok. Try now.

**Comment by MauriceMEGA65** [comment]
I believe this one can be closed, not?
 Works perfectly fine on my MEGA65.
